### ISSUE TITLE
cannot enable plugin

### ISSUE THREAD

**Issue by ShambreTaylor** [kraibse/obsidian-table-sorting#13] opened 2023-09-02 09:50 UTC
## Issue Description

I cannot enable the plugin.

## Steps to Reproduce

Probably i missed something beacuse of poor specific installing description.
So the detailed list of steps that Ive made:

1. Make a folder named table-sorting in .obsidian/plugins
2. Copy the main.ts, the manifest.json, and the styles.css into it
3. Refreshed the installed plugins in obsidian
4. Tried to enable the plugin

## Expected Behavior

Activation of the plugin

## Actual Behavior

Give an error: `Failed to load plugin table-sorting`

**Comment by kraibse** [comment] 2023-09-18 07:12
Hello, please excuse my late response.

I just did a clean install with a fresh vault and the latest release (1.3.0) of the plugin. It loads and works flawlessly on my end.

I'm sure there is an incompatible plugin somewhere. If you send me a list of your plugin I might be able to help you further.

**Comment by ShambreTaylor** [comment] 2023-09-18 08:53
Hello,
thank you.

The issue is still there with the 1.3.0. version of the plugin.

The most relevant plugins are (bcs I searched for the same feature):
- Advanced Tables - disabled
    (meanwhile I discovered that this plugin also has sorting functions) 
- Sortable - disabled

Should I send the other plugins?

**Comment by kraibse** [comment] 2023-09-18 09:33
Please do send me the other plugins. I think I remembered an incompatibility with Sortable, not sure if that still persists.
Also, is there anything else regarding this plugin in the console? Does it work for you in a fresh vault?

Depending on your needs you can use either advanced tables for sorting or this plugin. Keep in mind that obsidian-table-sorting keeps the original order of the values and can sort by multiple columns at the same time. Advanced tables is limited in that regard.

Other than that obsidian-table-sorting and the advanced tables plugin are compatible and I'd recommend having both activated.

**Comment by ShambreTaylor** [comment] 2023-09-19 12:54
Sure, here it is (more of them are not enabled, i do not know whether it is important):

- advanced-cursors  
- obsidian-completr            
- omnisearch
- colored-tags     
-  obsidian-editor-shortcuts    
- table-editor-obsidian
- colored-text      
- obsidian-kanban              
- table-sorting
- dataview         
-  obsidian-smarter-md-hotkeys  
- various-complements
- dbfolder          
- obsidian-sortable
- emoji-shortcodes  
- obsidian-underline

---

Thank you for the clarification of the uniqueness of your plugin.

**Comment by kraibse** [comment] 2023-09-29 06:43
So, I have looked through your list and compared it to the incompatibilities. I recommend disabling sortable since it reliably returns errors on my end as well. As I said with a clean vault and just the table sorting installed, my plugin works as intended with the latest version.

If the error persists after disabling / uninstalling sortable and doing a fresh install of obsidian-table-sorting, I recommend closing all open files with tables and reopening those files after restarting obsidian.

**Closed by kraibse** 2023-09-29 06:43 UTC
Labels: help wanted
